<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AS-40" name="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test" tests="6" failures="1" timestamp="2023-01-16T16:04:24 EET" time="56.977" errors="0">
  <testcase name="setup" time="5.507" classname="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test"/>
  <system-out/>
  <testcase name="loginTest" time="11.634" classname="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test"/>
  <system-out/>
  <testcase name="OpenRequest" time="14.569" classname="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test"/>
  <system-out/>
  <testcase name="SearchWithMobileNumber" time="16.537" classname="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test"/>
  <system-out/>
  <testcase name="checkCancelStatus" time="0.049" classname="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	status are equal expected [Cancelled] but found [Ongoing]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
status are equal expected [Cancelled] but found [Ongoing]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.ERA.PageObject.SearchCriteria.CheckCancelStatus(SearchCriteria.java:352)
at RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test.checkCancelStatus(Check_Status_Cancel_In_Admin_Test.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkCancelStatus -->
  <system-out/>
  <testcase name="GetRequestAndJobOrderID" time="8.681" classname="RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test"/>
  <system-out/>
</testsuite> <!-- RTA_FleetAndAdmin.Check_Status_Cancel_In_Admin_Test -->
